{
 "title": "coccapitalwatch",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "serveursql", "query": "mysql" }
  ]
 },
 "panels": [
  {
   "title": "global",
   "type": "table",
   "gridPos": { "h": 18, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "coc",
     "rawSql": "SELECT pseudo_joueur as pseudo, date_dernier_depot_joueur as \"date dernier depot\", contributions_joueur as \"contribution total\" FROM coc.joueurs LIMIT 50 "
    }
   ]
  },
  {
   "title": "donations",
   "type": "table",
   "gridPos": { "h": 18, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "dataset": "coc",
     "rawSql": "SELECT coc.joueurs.pseudo_joueur as pseudo, coc.depot.montant, coc.depot.date_depot as \"date de depot\" FROM coc.joueurs INNER JOIN coc.depot ON coc.joueurs.id_joueur = coc.depot.id_joueur ORDER BY coc.depot.date_depot DESC"
    }
   ]
  },
  {
   "title": "etat hall",
   "type": "table",
   "gridPos": { "h": 18, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "dataset": "coc",
     "rawSql": "SELECT somme_hall, date_hall FROM coc.halls ORDER BY date_hall DESC LIMIT 50 "
    }
   ]
  }
 ]
}